---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-client-k8s-deployment
spec:
  selector:
    matchLabels:
      app: dev-client-k8s
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: dev-client-k8s
    spec:
      containers:
        - name: dev-client-k8s
          image: registry.digitalocean.com/resty-registry/dev-client:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
          lifecycle:
            preStop:
              exec:
                command: ["/bin/bash", "-c", "sleep 120"]
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: dev-client-service
spec:
  selector:
    app: dev-client-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
