---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-client-k8s-deployment
spec:
  selector:
    matchLabels:
      app: prod-client-k8s
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: prod-client-k8s
    spec:
      containers:
        - name: prod-client-k8s
          image: registry.digitalocean.com/resty-registry/prod-client:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: prod-client-service
spec:
  selector:
    app: prod-client-k8s
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
