name: Deploy to Dev

#on: [push]
on:
  push:
    branches:
      - dev

env:
  REGISTRY: "registry.digitalocean.com/resty-registry"
  NGX_CLIENT: "client"

jobs:
  deploy:
    name: Build API image
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: executing git pull on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: resty
          key: ${{ secrets.SSHKEY }}
          port: 22
          command_timeout: 30m
          envs: NGX_CLIENT,GITHUB_SHA,REGISTRY
          script: |
            cd /home/resty/client
            git fetch
            git checkout dev
            git pull
            docker system prune -f --volumes
            docker build --no-cache -f Dockerfile.dev -t $(echo $REGISTRY)/$(echo $NGX_CLIENT):latest .

            doctl registry login
            isDisabled=true
            while $do; do
            do=false
            if doctl registry garbage-collection get-active; then
              docker push $(echo $REGISTRY)/$(echo $NGX_ADMIN):latest
              doctl registry garbage-collection start --include-untagged-manifests --force
              isDisabled=false
            else 
              echo "already running"
            fi
            done

            cd /home/resty/k8s
            kubectl apply -f cloudflared.yaml
            cd /home/resty/client
            kubectl delete -f client.k8s.yaml
            kubectl apply -f client.k8s.yaml
